name: 'citrusCLI'
description: 'CLI for citrusOS'
version: '1.0.0'
author: 'Citrusworx'
license: 'MIT'
language: 'en'
framework: 'TypeScript'
theme: ''
aws:
  id: ''
  s3: ''
  ec2: ''
  route53: ''
  acm: ''
  cognito: ''
  iam: ''
  lambda: ''
  dynamodb: ''
  sqs: ''
  sns: ''
  ses: ''
  s3Policy: ''
  ec2Policy: ''
  lambdaPolicy: ''
  dynamodbPolicy: ''
  sqsPolicy: ''
  snsPolicy: ''
  sesPolicy: ''
  acmPolicy: ''
  cognitoPolicy: ''
  iamPolicy: ''
  route53Policy: ''